server:
  port: ${SERVER_PORT}
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATA_BASE_URL}
    username: ${DATA_BASE_ID}
    password: ${DATA_BASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true